---
sudo: required

env:
  - distribution: ubuntu 
    version: xenial 

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile-ubuntu --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach -it --privileged -v /var/run/docker.sock:/var/run/docker.sock --volume="${PWD}":/etc/ansible/roles/goeth_role:rw ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/goeth_role/main.yml'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/goeth_role/tasks/start-geth.yml'
