---
sudo: required

env:
  - distribution: ubuntu 
    version: xenial 

services:
  - docker

before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install ansible
  - sudo pip install ansible-lint
script:
  - ansible-playbook main.yml
