---
sudo: required

env:
  - distribution: ubuntu 
    version: xenial 

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile-ubuntu --tag=${distribution}-${version}:ansible travis'
script:
  - container_id=$(mktemp)
  - 'docker exec -tty "${container_id}" docker run "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/goeth_role/travis/test.yml'


