sudo: required
env:
- distribution: ubuntu
  version: xenial
services:
- docker
addons:
  ssh_known_hosts: 52.90.245.146
before_install:
- sudo apt-get update -qq
install:
- sudo pip install ansible
- sudo pip install ansible-lint
- sudo pip install docker-compose
script:
- ansible-playbook main.yml
- pgrep 'geth' && (echo "Geth Running" && exit 0) || (echo "Geth Not Running" && exit
  1)
before_deploy:
- openssl aes-256-cbc -K $encrypted_0cc9b1ee0380_key -iv $encrypted_0cc9b1ee0380_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- sh travis/before_deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ansible-playbook main.yml -i inventory 
  on:
    branch: test-deploy
