---
- hosts: all

  tasks:
   - name: Create a goeth container
     docker_container:
       image: ethereum/client-go
       name: goeth 
       state: started
       privileged: true
       devices: /var/run/docker.sock:/var/run/docker.sock
   roles:
   - goeth_role
