---
- hosts: all

  tasks:
   - name: Create a goeth container
     docker_container:
       image: ethereum/client-go
       name: goeth 
       state: started
       privileged: true

  roles:
   - goeth_role
