---
- hosts: all

  tasks:
   - name: Ensure build dependencies are installed (Debian)
     package:
       name: "{{ item }}"
       state: present
     with_items:
       - build-essential
       - sudo
   - name: Create a goeth container
     docker_container:
       image: ethereum/client-go
       name: goeth 
       state: started
       privileged: true
  roles:
   - goeth_role
