---
- hosts: all

  tasks:
   # Start Docker Service
   - name: Start Docker service
     service: name=docker state=started
     become: yes
     become_method: sudo
   - name: Boot Docker on startup
     service: name=docker enabled=yes
     become: yes
     become_method: sudo
   - name: Create a goeth container
     docker_container:
       image: ethereum/client-go
       name: goeth 
       state: started

  roles:
   - goeth_role
