---
- hosts: all

  tasks:
   - name: Wait for Docker service to start    
     action: raw docker version
     register: docker_version
     until: docker_version.stdout.find("Client") != -1
     retries: 30
     delay: 10
     
   - name: Create a goeth container
     docker_container:
       image: ethereum/client-go
       name: goeth 
       state: started

  roles:
   - goeth_role
